apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: bartosz95/dice-game-api
        name: api
        command:
        - npm
        args:
        - run
        - start-prod
        ports:
        - name: container-port
          containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 2
          tcpSocket:
            port: container-port
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: container-port
        envFrom:
        - configMapRef:
            name: api-env
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret-env
              key: MONGO_INITDB_ROOT_PASSWORD
              optional: false
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret-env
              key: MONGO_INITDB_ROOT_USERNAME
              optional: false
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-env
              key: HOST
              optional: false
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-env
              key: PORT
              optional: false
        volumeMounts:
        - name: keycloak-json
          mountPath: /opt/dice-game-api/keycloak.json
          subPath: keycloak.json
          readOnly: true
      volumes:
      - name: keycloak-json
        configMap:
          name: api-keycloak-json