apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template: 
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: bartosz95/dice-game-api
        name: api
        command:
        - npm
        args:
        - run
        - start-prod
        envFrom:
        - configMapRef:
            name: api-env
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret-env
              key: MONGO_INITDB_ROOT_PASSWORD
              optional: false
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret-env
              key: MONGO_INITDB_ROOT_USERNAME
              optional: false
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo-env
              key: HOST
              optional: false
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongo-env
              key: PORT
              optional: false
        volumeMounts:
        - name: conf
          mountPath: /opt/dice-game-api/keycloak.json
          subPath: keycloak.json
          readOnly: true
        ports:
        - containerPort: 3000
      volumes:
      - name: conf
        configMap:
          name: keycloak-json