apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  labels: 
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template: 
    metadata:
      name: gui
      labels:
        app: gui
    spec:
      containers:
      - image:  bartosz95/dice-game-gui
        name:  gui
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: gui-env
        volumeMounts:
        - name: keycloak-json
          mountPath: /usr/share/nginx/html/keycloak.json
          subPath: keycloak.json
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      volumes:
      - name: keycloak-json
        configMap:
          name: keycloak-json
      - name: nginx-conf
        configMap:
          name: gui-nginx-conf