apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  labels: 
    app: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gui
  template: 
    metadata:
      name: gui
      labels:
        app: gui
    spec:
      containers:
      - image:  bartosz95/dice-game-gui
        name:  gui
        ports:
        - name: container-port
          containerPort: 80
        envFrom:
        - configMapRef:
            name: gui-env
        readinessProbe:
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 2
          httpGet:
            path: /
            port: container-port
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: /
            port: container-port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: keycloak-json
          mountPath: /usr/share/nginx/html/keycloak.json
          subPath: keycloak.json
          readOnly: true
        - name: config-json
          mountPath: /usr/share/nginx/html/config.json
          subPath: config.json
          readOnly: true
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      volumes:
      - name: keycloak-json
        configMap:
          name: gui-keycloak-json
      - name: config-json
        configMap:
          name: gui-config-json
      - name: nginx-conf
        configMap:
          name: gui-nginx-conf