apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gui
spec:
  tls:
    - hosts:
      - dice-game
  rules:
  - host: dice-game
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui
            port:
              number: 80