apiVersion: v1
kind: Service
metadata:
  name: gui
  labels:
    app: gui
spec:
  ports:
  - name: service-port
    port: 80
    protocol: TCP
    targetPort: container-port
  selector:
    app: gui
  type: LoadBalancer