apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: container-port
          containerPort: 27017
        readinessProbe:
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          successThreshold: 1
          failureThreshold: 2
          tcpSocket:
            port: container-port
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
          tcpSocket:
            port: container-port
        envFrom:
        - secretRef:
            name: mongo-secret-env
        volumeMounts:
        - name: data-dir
          mountPath: /var/mongo/data
      volumes:
      - name: data-dir
        persistentVolumeClaim:
          claimName: mongo-pvc
          