apiVersion: v1
kind: Service
metadata:
  name: ckey-admin
  labels:
    app: ckey-admin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ckey-admin
  type: LoadBalancer