apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        resources: {}
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret-env
        - configMapRef:
            name: postgres-env
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-dir
      volumes:
      - name: data-dir
        persistentVolumeClaim:
          claimName: postgres-pvc
status: {}