apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckey
  labels:
    app: ckey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckey
  template:
    metadata:
      labels:
        app: ckey
    spec:
      containers:
      - name: ckey
        image: bartosz95/ckey
        args: ["start --import-realm --optimized"]
        ports:
        - name: container-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: container-port
        envFrom:
        - secretRef:
            name: ckey-secret-env
        - configMapRef:
            name: ckey-env
        env:
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret-env
              key: POSTGRES_USER
              optional: false
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-env
              key: POSTGRES_PASSWORD
              optional: false
        volumeMounts:
        - name: dice-game-realm-json
          mountPath: "/opt/keycloak/data/import"
          readOnly: true
      volumes:
      - name: dice-game-realm-json
        configMap:
          name: ckey-dice-game-realm-json