apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bartosz95/ckey
        args: ["start --import-realm --optimized"]
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        envFrom:
        - secretRef:
            name: ckey-secret-env
        - configMapRef:
            name: ckey-env
        env:
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret-env
              key: POSTGRES_USER
              optional: false
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret-env
              key: POSTGRES_PASSWORD
              optional: false
        volumeMounts:
        - name: conf
          mountPath: "/opt/keycloak/data/import"
          readOnly: true
      volumes:
      - name: conf
        configMap:
          name: bolo-realm