apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
      - dice-game-auth
  rules:
  - host: dice-game-auth
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ckey
            port:
              number: 80