apiVersion: v1
kind: Service
metadata:
  name: ckey
  labels:
    app: ckey
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ckey
  type: LoadBalancer